FROM resin/%%RESIN_MACHINE_NAME%%-python:3.3.1-slim

WORKDIR /usr/src/app

COPY ./app/requirements.txt ./

RUN apt-get update && apt-get install -yq --no-install-recommends \
  python sense-hat raspberrypi-bootloader && \
  pip install sense-hat rtimulib && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./app ./

## Uncomment if you want systemd
ENV INITSYSTEM on

# Start app
CMD ["python", "/usr/src/app/app.py"]
